feat(bin): pango colours for battery life in sway_status script

diff --git a/bin/.local/bin/sway_status b/bin/.local/bin/sway_status
--- a/bin/.local/bin/sway_status
+++ b/bin/.local/bin/sway_status
@@ -1,99 +1,148 @@
 #!/bin/sh
-# Change this according to your device
-################
-# Variables
-################
 
-# Keyboard input name
-keyboard_input_name="1:1:AT_Translated_Set_2_keyboard"
+notice="yellow"
+warning="orange"
+critical="red"
 
-# Date and time
-date=$(date "+%d %b")
-current_time=$(date "+%H:%M")
+usage() {
+    echo "Usage: $0 [OPTIONS]"
+    echo "Options:"
+    echo "-h|--help             Print this usage message"
+    echo "   --notice COLOR     Specify a color for notice events (default: yellow)"
+    echo "   --warning COLOR    Specify a color for warning events (default: orange)"
+    echo "   --critical COLOR   Specify a color for critical events (default: red)"
+}
 
-#############
-# Commands
-#############
+has_argument() {
+    [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*)  ]];
+}
 
-# Battery or charger
-battery_charge=$(upower --show-info $(upower --enumerate | grep 'BAT') | grep -E "percentage" | awk '{print $2}')
-battery_status=$(upower --show-info $(upower --enumerate | grep 'BAT') | grep -E "state" | awk '{print $2}')
+extract_argument() {
+    echo "${2:-${1#*=}}"
+}
 
-# Audio and multimedia
-audio_volume=$(pamixer --sink `pactl list sinks short | grep RUNNING | awk '{print $1}'` --get-volume)
-audio_is_muted=$(pamixer --sink `pactl list sinks short | grep RUNNING | awk '{print $1}'` --get-mute)
-media_artist=$(playerctl metadata artist)
-media_song=$(playerctl metadata title)
-player_status=$(playerctl status)
+handle_options() {
+    while [ $# -gt 0 ]; do 
+        case $1 in
+            -h|--help)
+                usage
+                exit 0
+            ;;
+            --notice*)
+                if ! has_argument $@; then
+                    echo "color for notice not specified" >&2
+                    usage
+                    exit 1
+                fi
+                notice=$(extract_argument $@)
+                shift
+            ;;
+            --warning*)
+                if ! has_argument $@; then
+                    echo "color for warning not specified" >&2
+                    usage
+                    exit 1
+                fi
+                warning=$(extract_argument $@)
+                shift
+            ;;
+            --critical*)
+                if ! has_argument $@; then
+                    echo "color for critical not specified" >&2
+                    usage
+                    exit 1
+                fi
+                critical=$(extract_argument $@)
+                shift
+            ;;
+            *)
+                echo "invalid option: $1" >&2
+                usage
+                exit 1
+            ;;
+        esac
+        shift
+    done
+}
 
-# Network
-network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+' | cut -f1 -d ' ')
-# interface_easyname grabs the "old" interface name before systemd renamed it
-interface_easyname=$(dmesg | grep $network | grep renamed | awk 'NF>1{print $NF}')
+handle_options "$@"
 
-# Others
-language=$(swaymsg -r -t get_inputs | awk '/1:1:AT_Translated_Set_2_keyboard/;/xkb_active_layout_name/' | grep -A1 '\b1:1:AT_Translated_Set_2_keyboard\b' | grep "xkb_active_layout_name" | awk -F '"' '{print $4}')
-loadavg_5min=$(cat /proc/loadavg | awk -F ' ' '{print $2}')
+music_player() {
+    media_artist=$(playerctl metadata artist)
+    media_song=$(playerctl metadata title)
+    player_status=$(playerctl status)
 
-# Removed weather because we are requesting it too many times to have a proper
-# refresh on the bar
-#weather=$(curl -Ss 'https://wttr.in/Pontevedra?0&T&Q&format=1')
-
-battery_charge_icon="󰂄"
-if [ $battery_status = "discharging" ]; then
-    battery_charge_num=${battery_charge%\%}
-    if [ $battery_charge_num -ge 95 ]; then
-        battery_charge_icon="󰁹"
-    elif [ $battery_charge_num -ge 90 ]; then
-        battery_charge_icon="󰂂"
-    elif [ $battery_charge_num -ge 80 ]; then
-        battery_charge_icon="󰂁"
-    elif [ $battery_charge_num -ge 70 ]; then
-        battery_charge_icon="󰂀"
-    elif [ $battery_charge_num -ge 60 ]; then
-        battery_charge_icon="󰁿"
-    elif [ $battery_charge_num -ge 50 ]; then
-        battery_charge_icon="󰁾"
-    elif [ $battery_charge_num -ge 40 ]; then
-        battery_charge_icon="󰁽"
-    elif [ $battery_charge_num -ge 30 ]; then
-        battery_charge_icon="󰁼"
-    elif [ $battery_charge_num -ge 20 ]; then
-        battery_charge_icon="󰁻"
-    elif [ $battery_charge_num -ge 10 ]; then
-        battery_charge_icon="󰁺"
+    if [ "$player_status" = "Playing" ]; then
+        song_status='▶'
+    elif [ "$player_status" = "Paused" ]; then
+        song_status='⏸'
     else
-        battery_charge_icon="󰂎"
+        song_status='⏹'
     fi
-fi
+
+    if [ ${#media_song} -gt 25 ]; then
+        media_song="${media_song:0:22}..."
+    fi
+
+    echo " $song_status $media_artist - $media_song"
+}
+
+network() {
+    network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+' | cut -f1 -d ' ')
+    interface_easyname=$(dmesg | grep $network | grep renamed | awk 'NF>1{print $NF}')
+
+    if ! [ $network ]; then
+       network_active="⛔"
+    else
+       network_active="⇆"
+    fi
+    echo "$network_active $interface_easyname"
+}
+
+loadavg() {
+    echo " $(cat /proc/loadavg | awk -F ' ' '{print $2}')"
+}
+
+volume() {
+    audio_volume=$(pamixer --sink `pactl list sinks short | grep RUNNING | awk '{print $1}'` --get-volume)
+    audio_is_muted=$(pamixer --sink `pactl list sinks short | grep RUNNING | awk '{print $1}'` --get-mute)
+
+    if [ "$audio_volume" = "" ]; then
+        audio_volume="0"
+    fi
+
+    if [ "$audio_is_muted" = "true" ]; then
+        audio_active=''
+    else
+        audio_active=''
+    fi
+
+    echo "$audio_active $audio_volume%"
+}
+
+battery_charge() {
+    battery_charge=$(upower --show-info $(upower --enumerate | grep 'BAT') | grep -E "percentage" | awk '{print $2}')
+    battery_status=$(upower --show-info $(upower --enumerate | grep 'BAT') | grep -E "state" | awk '{print $2}')
+
+    battery_charge_icons=( "󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹" )
+    colors=( "" $critical $warning $notice )
+    battery_charge_icon="󰂄"
+    if [ $battery_status = "discharging" ]; then
+        battery_charge_num=${battery_charge%\%}
+        battery_charge_icon=${battery_charge_icons[$(($battery_charge_num / 10))]}
+        color=${colors[$((1 + $battery_charge_num / 10))]}
+    fi
+
+    if [ -z $color ]; then
+        echo "$battery_charge $battery_charge_icon"
+    else
+        echo "<span foreground='$color'>$battery_charge $battery_charge_icon</span>"
+    fi
+}
+
+datetime() {
+    echo " $(date '+%d %b') 󰥔 $(date '+%H:%M')"
+}
 
 
-if ! [ $network ]; then
-   network_active="⛔"
-else
-   network_active="⇆"
-fi
-
-if [ $player_status = "Playing" ]; then
-    song_status='▶'
-elif [ $player_status = "Paused" ]; then
-    song_status='⏸'
-else
-    song_status='⏹'
-fi
-
-if [ ${#audio_volume} == 0 ]; then
-    audio_volume="0"
-fi
-
-if [ $audio_is_muted = "true" ]; then
-    audio_active=''
-else
-    audio_active=''
-fi
-
-if [ ${#media_song} -gt 25 ]; then
-    media_song="${media_song:0:22}..."
-fi
-
-echo " $song_status $media_artist - $media_song | $network_active $interface_easyname |   $loadavg_5min | $audio_active   $audio_volume% | $battery_pluggedin $battery_charge $battery_charge_icon   |   $date 󰥔  $current_time"
+echo "$(music_player) | $(network) | $(loadavg) | $(volume) | $(battery_charge) | $(datetime)"
